#!/bin/sh
#
# gkrellmd	gkrellmd - The GNU Krell Monitors Server
#
# chkconfig:    345 95 10
#
# description:	gkrellmd Listens for connections from gkrellm clients.  When a  gkrellm
#		client connects to a gkrellmd server all builtin monitors collect their
#		data from the server.
#
# processname:	gkrellmd
# config:	/etc/gkrellmd.conf
# pidfile:	/var/run/gkrellmd.pid
#
# $Id$


# Source function library
. /etc/rc.d/init.d/functions

# Get network config
. /etc/sysconfig/network

# Set defaults
OPTIONS="-d"

# Get service config - may override defaults
[ -f /etc/sysconfig/gkrellmd ] && . /etc/sysconfig/gkrellmd

# Check that networking is up.
if is_yes "${NETWORKING}"; then
	if [ ! -f /var/lock/subsys/network ]; then
		# nls "ERROR: Networking is down. %s can't be run." gkrellmd
		msg_network_down gkrellmd
		exit 1
	fi
else
	exit 0
fi

RETVAL=0
# See how we were called.
case "$1" in
  start)
	if [ ! -f /var/lock/subsys/gkrellmd ]; then
		msg_starting gkrellmd
		daemon gkrellmd $OPTIONS
		RETVAL=$?
		[ $RETVAL -eq 0 ] && touch /var/lock/subsys/gkrellmd
	else
		msg_already_running gkrellmd
	fi
        ;;
  stop)
	if [ -f /var/lock/subsys/gkrellmd ]; then
		msg_stopping gkrellmd
		killproc gkrellmd
		rm -f /var/lock/subsys/gkrellmd
	else
		msg_not_running gkrellmd
	fi	
        ;;
  restart|force-reload)
        $0 stop
	$0 start
	exit $?
        ;;
  status)
	status gkrellmd
	exit $?
        ;;
  *)
	msg_usage "$0 {start|stop|restart|force-reload|status}"
        exit 3
esac

exit $RETVAL

# This must be last line !
# vi:syntax=sh:tw=78:ts=8:sw=4
